# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6328d4ec047c374ce002caa34489b56670c1ead2d5392477857014e86a2b7ea0c643e4fd5731bb71841e0c013b66a1f8ed95babccc9a59f92989d103a81d2105

test:
  secret_key_base: 2af3aaa7acf876bb6d25f5d9d3f5747887df61796abe6a8a43c4f28d4fbce9da89aa82fb8f74a1b01e476a0687fc2ba3e73ad9ae929f84e26f0a146f1eb2098d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
